# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
pr: none

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Backend: build'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'windows-latest'

    variables:
      dotnetSdkVersion: '3.1.100'

    steps:
    - task: UseDotNet@2
      displayName: 'Usando .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restaurando dependências do projeto'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Buildando o projeto como $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'
        
    - task: DotNetCoreCLI@2
      displayName: 'Publicando o projeto como $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.WebApi.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop
      
- stage: 'Test'
  displayName: 'Deploy para testes'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: tests-backend
    variables:
    - group: Testes
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Deploy para o web app da API'
            inputs:
              azureSubscription: 'DeliveryBr - App Service Test'
              appName: '$(WebAppApi)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'